{
    "name": "Sitrep CI",
    "on": [ "push" ],
    "jobs": {
        "build": {
            "runs-on": "ubuntu-latest",
            "steps": [
                { "uses": "actions/checkout@v1" },
                {
                    "name": "Install Nix",
                    "run": "nix/install --daemon"
                },
                {
                    "name": "Build Sitrep",
                    "run": "/nix/var/nix/profiles/default/bin/nix run -ic snowflake build.pl sitrep"
                },
                {
                    "name": "Run unit tests",
                    "run": "UNITTEST=Y build/artifact/sitrep-sitrep-receive/sitrep-receive"
                },
                {
                    "name": "Run integration tests",
                    "run": "/nix/var/nix/profiles/default/bin/nix run -ic env INTEGRATIONTEST=Y build/artifact/sitrep-hivemind.bash/hivemind.bash && (exit \"$(< state/prove.status)\")"
                }
            ]
        }
    }
}
